### ISSUE TITLE
Docs feedback

### ISSUE THREAD

**Issue by Alternikaner** [spielmanlab/introverse#22]
**Which topic are you filing an issue about?**
The pkgdown site has a broken link (On the Get Help in RStudio page, under "What topics can I get help on"):

Or, all currently available topics can be seen [here](https://spielmanlab.github.io/introverse/articles/available_topics.html)

**Place an X in the appropriate column:**

For example, 
- [x] This is checked
- [ ] This is unchecked 

--------------------------------------

- [ ] There is a typo in the textual explanations and/or conceptual usage
- [ ] There is a bug in the example code or comments
- [ ] You find at least one existing code example is unclear
- [ ] You have suggestion(s) for additional code example(s) that would improve the docs
- [ ] Parts of the textual explanations are unclear

**Explain your feedback and any suggested changes.**

**Are you interested in addressing these concerns with a Pull Request (yes or no)?**
[](url)

**Comment by sjspielman** [comment]
Thanks @Alternikaner!! Will fix that today!

**Comment by sjspielman** [comment]
Done, thanks again for catching this!
